def game_data():[
    """
    This contains all the questions and answers
    """
    {"question": "Who are the main two characters?",
     "answers": {"A": "Mike and Ike",
                 "B": "Sam and Dean",
                 "C": "Lou and Moe"},
     "correct_answer": "B"},
    {"question": "What was Sam studying in Stanford?",
     "answers": {"A": "Law",
                 "B": "Accounting",
                 "C": "Business"},
     "correct_answer": "A"},
    {"question": "In the episode “The Slice Girls” what was Deans Daughters name?",
     "answers": {"A": "Emma",
                 "B": "Amanda",
                 "C": "Jenny"},
     "correct_answer": "A"},
    {"question": "In the episode “Yellow Fever” what happened to Dean?",
     "answers": {"A": "He gets shot",
                 "B": "He gets stabbed",
                 "C": "He gets haunted"},
     "correct_answer": "C"},
    {"question": "What does Sam add to Deans car?",
     "answers": {"A": "A new radio",
                 "B": "An IPod jack",
                 "C": "A drink holder"},
     "correct_answer": "B"},
    {"question": "When the apocalypse starts who is the first horseman they face?",
     "answers": {"A": "Death",
                 "B": "Famine",
                 "C": "War"},
     "correct_answer": "C"},
    {"question": "How many meat suits has Ruby had?",
     "answers": {"A": "Four",
                 "B": "Six",
                 "C": "One"},
     "correct_answer": "A"},
    {"question": "What are Crowley’s nick names for the boys?",
     "answers": {"A": "Shaggy and Scooby",
                 "B": "Moose and Squirrel",
                 "C": "Mouse and Elephant"},
     "correct_answer": "B"},
    {"question": "How many things cannot be killed by the Colt?",
     "answers": {"A": "Eight",
                 "B": "Two",
                 "C": "Five"},
     "correct_answer": "C"},
    {"question": "What was the name of Sams dog (when Dean was missing)??",
     "answers": {"A": "Rover",
                 "B": "Spot",
                 "C": "Riot"},
     "correct_answer": "C"},
    {"question": "What car does Dean drive?",
     "answers": {"A": "`69 Chevy Impala",
                 "B": "`67 Chevy Impala",
                 "C": "`69 Ford Mustang"},
     "correct_answer": "B"},
    {"question": "What is the family business?",
     "answers": {"A": "Saving people, hunting things.",
                 "B": "Helping people, killing monsters",
                 "C": "Helping people, hunting things."},
     "correct_answer": "A"},
    {"question": "What is the name of Castiel`s vessles wife??",
     "answers": {"A": "Anne Novak",
                 "B": "Amelia Novak",
                 "C": "Sarah Novak"},
     "correct_answer": "B"},
    {"question": "How many Winchesters have appeared on the show?",
     "answers": {"A": "Six",
                 "B": "Eight",
                 "C": "Two"},
     "correct_answer": "A"},
    {"question": "What are the names of the 4 Princes of Hell?",
     "answers": {"A": "Azreal, Rancial, Dagron, Amrodus",
                 "B": "Azreal, Rheagon, Damrus, Asphodel",
                 "C": "Azazel, Ramiel, Dagon, Asmodeus"},
     "correct_answer": "C"},
    {"question": "What was the first “thing” the boys faced in the “Pilot” episode?",
     "answers": {"A": "A Wendigo",
                 "B": "Woman in white",
                 "C": "A Trickster"},
     "correct_answer": "B"},
    {"question": "In the episode “in the beginning” what year is Dean sent to?",
     "answers": {"A": "1969",
                 "B": "1943",
                 "C": "1973"},
     "correct_answer": "C"},
    {"question": "Where is the bunker that the boys call home from season 8?",
     "answers": {"A": "Kansas",
                 "B": "Denver",
                 "C": "Nebraska"},
     "correct_answer": "A"},
    {"question": "Which figures (Biblical) are the boys related to?",
     "answers": {"A": "Cain and Abel",
                 "B": "Jacob and Rachel",
                 "C": "Moses and Abraham"},
     "correct_answer": "A"},
    {"question": "Charlie has a figurine of which character on her desk?",
     "answers": {"A": "Princess Peach",
                 "B": "Hermione Granger",
                 "C": "Golum"},
     "correct_answer": "B"},
    ]