def game_data():[
    """
    This contains all the questions and answers
    """
    {"question": "Who are the main two characters?",
     "answers": {"A": "Mike and Ike",
                 "B": "Sam and Dean",
                 "C": "Lou and Moe"},
     "correct_answer": "B"},
    {"question": "What was Sam studying in Stanford?",
     "answers": {"A": "Law",
                 "B": "Accounting",
                 "C": "Business"},
     "correct_answer": "A"},
    {"question": "In the episode “The Slice Girls” what was Deans Daughters name?",
     "answers": {"A": "Emma",
                 "B": "Amanda",
                 "C": "Jenny"},
     "correct_answer": "A"},
    {"question": "In the episode “Yellow Fever” what happened to Dean?",
     "answers": {"A": "He gets shot",
                 "B": "He gets stabbed",
                 "C": "He gets haunted"},
     "correct_answer": "C"},
    {"question": "What does Sam add to Deans car?",
     "answers": {"A": "A new radio",
                 "B": "An IPod jack",
                 "C": "A drink holder"},
     "correct_answer": "B"},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    {"question": "?",
     "answers": {"A": "",
                 "B": "",
                 "C": ""},
     "correct_answer": ""},
    ]